apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-n-foodious-pvc
spec:
  resources:
    requests:
      storage: 300Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-n-foodious-storage