apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    app: fluentd
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  serviceAccount: fluentd
  serviceAccountName: fluentd
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          namespace: kube-system
          image: opsdockerimage/fluentd-elasticsearch:v2.4.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: FLUENT_UID
              value: "0"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: var/lib/docker/containers
              readOnly: true
            - name: fluentd-conf
              mountPath: /etc/fluent
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluentd-conf
          configMap:
            name: fluentd-env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-env
  namespace: kube-system
labels:
   name: fluentd-env
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>

    <match kubernetes.**>
      @type elasticsearch
      host elasticsearch-svc.default.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix kubernetes
      include_tag_key true
      tag_key @log_name
      flush_interval 5s
    </match>